"""Added token model

Revision ID: 703182710a82
Revises: bd6158d816f3
Create Date: 2020-12-01 11:32:58.594908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703182710a82'
down_revision = 'bd6158d816f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('controller_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['controller_id'], ['controllers.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
